WIKI_PAGES_TABLE = 'wiki_pages'
WIKI_PAGES_PRIMARY_KEY  = 'id'
WIKI_PAGES_TITLE_KEY = 'title'
WIKI_PAGES_URL_KEY = 'url'

WIKI_CONTENTS_TABLE = 'wiki_contents'
WIKI_CONTENTS_PRIMARY_KEY = 'id'
WIKI_CONTENTS_TEXT_KEY = 'text'

WIKI_TOKENIZED_TABLE = 'wiki_tokenized'
WIKI_TOKENIZED_PRIMARY_KEY = 'id'
WIKI_TOKENIZED_WAKATI_TEXT_KEY = 'wakati_text'
